Completed homework 1
TimaFrolov/programmingPracticeInSPbU pull request #1
Opened 2022-09-09 16:24 UTC by TimaFrolov

2022-09-12 18:07 UTC, Lozov-Petr requested changes

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_1.c
> +    int x;
Для полнинома ожидается скорее тип с плавающей запятой

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_2.c
> +    else
Зачем ветка else?

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_2.c
> +        if ((powersOfTwo[i] + quotient) * (long long)divider <= dividend)
Объясни на паре, зачем приведение типов.

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_2.c
> +    const int powersOfTwo[] = {1073741824, 536870912, 268435456, 134217728, 67108864, 33554432,
Неплохое решение, но массив степеней двоек - не хорошо.

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_2.c
> +        return 0;
Разве при делителе равном нулю такой результат?

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_4.c
> +ushort countTickets()
Расскажи про это решение на паре в пятницу

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_5.c
> +                stack = realloc(stack, (i + strSize) * sizeof(char));
Что-то странное. Новый размер стека должен зависить от текущего размера, а не от количества прочитанных символов.

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_5.c
> +    else
Зачем else?

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_6.c
> +    str[sLen] = '\036'; // record separator symbol, hope s and s1 doesn't contain it
Стоит явно проверить, что строка не содержит этот символ. И предупредить пользователя.

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_6.c
> +    reverse(sLen, str + s1Len + 1);
Зачем?

2022-09-12 18:07 UTC, Lozov-Petr commented on homework1/task_7.c
> +    printf("Enter number: ");
По выводимому тексту программы непонятно, что она на вход принемает, и что возвращает.
Ты ей "-333", а она тебе "\n".

2022-09-12 18:10 UTC, Lozov-Petr commented on homework1/task_6.c
> +    str[sLen] = '\036'; // record separator symbol, hope s and s1 doesn't contain it
А лучше вообще не завязываться на символ, который может быть во входной строке.

2022-09-12 19:01 UTC, TimaFrolov commented on homework1/task_2.c
> +    const int powersOfTwo[] = {1073741824, 536870912, 268435456, 134217728, 67108864, 33554432,
Можно взять переменную, изначально равную 2^30, и потом в цикле битшифтом уменьшать в два раза, но условиями задачи это запрещено. Другого способа проделать то же (помимо массива) я не придумал

2022-09-17 19:39 UTC, Lozov-Petr commented on homework1/task_2.c
> +    const int powersOfTwo[] = {1073741824, 536870912, 268435456, 134217728, 67108864, 33554432,
Сделай со сдвигом) Выйдем за условия, зато красиво получится.

2022-09-18 14:03 UTC, merged